// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPISecurityOpenAPISpecsCatalogIDParams creates a new DeleteAPISecurityOpenAPISpecsCatalogIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPISecurityOpenAPISpecsCatalogIDParams() *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	return &DeleteAPISecurityOpenAPISpecsCatalogIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithTimeout creates a new DeleteAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithTimeout(timeout time.Duration) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	return &DeleteAPISecurityOpenAPISpecsCatalogIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithContext creates a new DeleteAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a context for a request.
func NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithContext(ctx context.Context) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	return &DeleteAPISecurityOpenAPISpecsCatalogIDParams{
		Context: ctx,
	}
}

// NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithHTTPClient creates a new DeleteAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPISecurityOpenAPISpecsCatalogIDParamsWithHTTPClient(client *http.Client) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	return &DeleteAPISecurityOpenAPISpecsCatalogIDParams{
		HTTPClient: client,
	}
}

/* DeleteAPISecurityOpenAPISpecsCatalogIDParams contains all the parameters to send to the API endpoint
   for the delete API security open API specs catalog ID operation.

   Typically these are written to a http.Request.
*/
type DeleteAPISecurityOpenAPISpecsCatalogIDParams struct {

	// CatalogID.
	//
	// Format: uuid
	CatalogID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API security open API specs catalog ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WithDefaults() *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API security open API specs catalog ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WithTimeout(timeout time.Duration) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WithContext(ctx context.Context) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WithHTTPClient(client *http.Client) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogID adds the catalogID to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WithCatalogID(catalogID strfmt.UUID) *DeleteAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the delete API security open API specs catalog ID params
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) SetCatalogID(catalogID strfmt.UUID) {
	o.CatalogID = catalogID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPISecurityOpenAPISpecsCatalogIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param catalogId
	if err := r.SetPathParam("catalogId", o.CatalogID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
