// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPISecurityAPICatalogIDReader is a Reader for the DeleteAPISecurityAPICatalogID structure.
type DeleteAPISecurityAPICatalogIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPISecurityAPICatalogIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPISecurityAPICatalogIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAPISecurityAPICatalogIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPISecurityAPICatalogIDNoContent creates a DeleteAPISecurityAPICatalogIDNoContent with default headers values
func NewDeleteAPISecurityAPICatalogIDNoContent() *DeleteAPISecurityAPICatalogIDNoContent {
	return &DeleteAPISecurityAPICatalogIDNoContent{}
}

/* DeleteAPISecurityAPICatalogIDNoContent describes a response with status code 204, with default header values.

Success
*/
type DeleteAPISecurityAPICatalogIDNoContent struct {
}

func (o *DeleteAPISecurityAPICatalogIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /apiSecurity/api/{catalogId}][%d] deleteApiSecurityApiCatalogIdNoContent ", 204)
}

func (o *DeleteAPISecurityAPICatalogIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPISecurityAPICatalogIDUnauthorized creates a DeleteAPISecurityAPICatalogIDUnauthorized with default headers values
func NewDeleteAPISecurityAPICatalogIDUnauthorized() *DeleteAPISecurityAPICatalogIDUnauthorized {
	return &DeleteAPISecurityAPICatalogIDUnauthorized{}
}

/* DeleteAPISecurityAPICatalogIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type DeleteAPISecurityAPICatalogIDUnauthorized struct {
}

func (o *DeleteAPISecurityAPICatalogIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apiSecurity/api/{catalogId}][%d] deleteApiSecurityApiCatalogIdUnauthorized ", 401)
}

func (o *DeleteAPISecurityAPICatalogIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
