// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPISecurityOpenAPISpecsCatalogIDParams creates a new GetAPISecurityOpenAPISpecsCatalogIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPISecurityOpenAPISpecsCatalogIDParams() *GetAPISecurityOpenAPISpecsCatalogIDParams {
	return &GetAPISecurityOpenAPISpecsCatalogIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithTimeout creates a new GetAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a timeout on a request.
func NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithTimeout(timeout time.Duration) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	return &GetAPISecurityOpenAPISpecsCatalogIDParams{
		timeout: timeout,
	}
}

// NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithContext creates a new GetAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a context for a request.
func NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithContext(ctx context.Context) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	return &GetAPISecurityOpenAPISpecsCatalogIDParams{
		Context: ctx,
	}
}

// NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithHTTPClient creates a new GetAPISecurityOpenAPISpecsCatalogIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPISecurityOpenAPISpecsCatalogIDParamsWithHTTPClient(client *http.Client) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	return &GetAPISecurityOpenAPISpecsCatalogIDParams{
		HTTPClient: client,
	}
}

/* GetAPISecurityOpenAPISpecsCatalogIDParams contains all the parameters to send to the API endpoint
   for the get API security open API specs catalog ID operation.

   Typically these are written to a http.Request.
*/
type GetAPISecurityOpenAPISpecsCatalogIDParams struct {

	// CatalogID.
	//
	// Format: uuid
	CatalogID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API security open API specs catalog ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WithDefaults() *GetAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API security open API specs catalog ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WithTimeout(timeout time.Duration) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WithContext(ctx context.Context) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WithHTTPClient(client *http.Client) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogID adds the catalogID to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WithCatalogID(catalogID strfmt.UUID) *GetAPISecurityOpenAPISpecsCatalogIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the get API security open API specs catalog ID params
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) SetCatalogID(catalogID strfmt.UUID) {
	o.CatalogID = catalogID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPISecurityOpenAPISpecsCatalogIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param catalogId
	if err := r.SetPathParam("catalogId", o.CatalogID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
