// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"io"
	"github.com/cisco-developer/api-insights/api/pkg/panoptica/models"
)

// GetAPISecurityExternalCatalogCatalogIDReader is a Reader for the GetAPISecurityExternalCatalogCatalogID structure.
type GetAPISecurityExternalCatalogCatalogIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPISecurityExternalCatalogCatalogIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPISecurityExternalCatalogCatalogIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPISecurityExternalCatalogCatalogIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPISecurityExternalCatalogCatalogIDOK creates a GetAPISecurityExternalCatalogCatalogIDOK with default headers values
func NewGetAPISecurityExternalCatalogCatalogIDOK() *GetAPISecurityExternalCatalogCatalogIDOK {
	return &GetAPISecurityExternalCatalogCatalogIDOK{}
}

/* GetAPISecurityExternalCatalogCatalogIDOK describes a response with status code 200, with default header values.

Success
*/
type GetAPISecurityExternalCatalogCatalogIDOK struct {
	Payload *models.APIServiceDrillDownExternal
}

func (o *GetAPISecurityExternalCatalogCatalogIDOK) Error() string {
	return fmt.Sprintf("[GET /apiSecurity/externalCatalog/{catalogId}][%d] getApiSecurityExternalCatalogCatalogIdOK  %+v", 200, o.Payload)
}
func (o *GetAPISecurityExternalCatalogCatalogIDOK) GetPayload() *models.APIServiceDrillDownExternal {
	return o.Payload
}

func (o *GetAPISecurityExternalCatalogCatalogIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIServiceDrillDownExternal)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPISecurityExternalCatalogCatalogIDUnauthorized creates a GetAPISecurityExternalCatalogCatalogIDUnauthorized with default headers values
func NewGetAPISecurityExternalCatalogCatalogIDUnauthorized() *GetAPISecurityExternalCatalogCatalogIDUnauthorized {
	return &GetAPISecurityExternalCatalogCatalogIDUnauthorized{}
}

/* GetAPISecurityExternalCatalogCatalogIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type GetAPISecurityExternalCatalogCatalogIDUnauthorized struct {
}

func (o *GetAPISecurityExternalCatalogCatalogIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apiSecurity/externalCatalog/{catalogId}][%d] getApiSecurityExternalCatalogCatalogIdUnauthorized ", 401)
}

func (o *GetAPISecurityExternalCatalogCatalogIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
