// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"io"
	"github.com/cisco-developer/api-insights/api/pkg/panoptica/models"
)

// GetAPISecurityExternalCatalogReader is a Reader for the GetAPISecurityExternalCatalog structure.
type GetAPISecurityExternalCatalogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPISecurityExternalCatalogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPISecurityExternalCatalogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPISecurityExternalCatalogUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPISecurityExternalCatalogOK creates a GetAPISecurityExternalCatalogOK with default headers values
func NewGetAPISecurityExternalCatalogOK() *GetAPISecurityExternalCatalogOK {
	return &GetAPISecurityExternalCatalogOK{}
}

/* GetAPISecurityExternalCatalogOK describes a response with status code 200, with default header values.

Success
*/
type GetAPISecurityExternalCatalogOK struct {
	Payload *models.APIServiceListExternal
}

func (o *GetAPISecurityExternalCatalogOK) Error() string {
	return fmt.Sprintf("[GET /apiSecurity/externalCatalog][%d] getApiSecurityExternalCatalogOK  %+v", 200, o.Payload)
}
func (o *GetAPISecurityExternalCatalogOK) GetPayload() *models.APIServiceListExternal {
	return o.Payload
}

func (o *GetAPISecurityExternalCatalogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIServiceListExternal)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPISecurityExternalCatalogUnauthorized creates a GetAPISecurityExternalCatalogUnauthorized with default headers values
func NewGetAPISecurityExternalCatalogUnauthorized() *GetAPISecurityExternalCatalogUnauthorized {
	return &GetAPISecurityExternalCatalogUnauthorized{}
}

/* GetAPISecurityExternalCatalogUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type GetAPISecurityExternalCatalogUnauthorized struct {
}

func (o *GetAPISecurityExternalCatalogUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apiSecurity/externalCatalog][%d] getApiSecurityExternalCatalogUnauthorized ", 401)
}

func (o *GetAPISecurityExternalCatalogUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
