// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"net/http"
	"time"
	"github.com/cisco-developer/api-insights/api/pkg/panoptica/models"
)

// NewPostAPISecurityAPIParams creates a new PostAPISecurityAPIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPISecurityAPIParams() *PostAPISecurityAPIParams {
	return &PostAPISecurityAPIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPISecurityAPIParamsWithTimeout creates a new PostAPISecurityAPIParams object
// with the ability to set a timeout on a request.
func NewPostAPISecurityAPIParamsWithTimeout(timeout time.Duration) *PostAPISecurityAPIParams {
	return &PostAPISecurityAPIParams{
		timeout: timeout,
	}
}

// NewPostAPISecurityAPIParamsWithContext creates a new PostAPISecurityAPIParams object
// with the ability to set a context for a request.
func NewPostAPISecurityAPIParamsWithContext(ctx context.Context) *PostAPISecurityAPIParams {
	return &PostAPISecurityAPIParams{
		Context: ctx,
	}
}

// NewPostAPISecurityAPIParamsWithHTTPClient creates a new PostAPISecurityAPIParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPISecurityAPIParamsWithHTTPClient(client *http.Client) *PostAPISecurityAPIParams {
	return &PostAPISecurityAPIParams{
		HTTPClient: client,
	}
}

/* PostAPISecurityAPIParams contains all the parameters to send to the API endpoint
   for the post API security API operation.

   Typically these are written to a http.Request.
*/
type PostAPISecurityAPIParams struct {

	// Body.
	Body *models.APISecurityAPI

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API security API params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISecurityAPIParams) WithDefaults() *PostAPISecurityAPIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API security API params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISecurityAPIParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API security API params
func (o *PostAPISecurityAPIParams) WithTimeout(timeout time.Duration) *PostAPISecurityAPIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API security API params
func (o *PostAPISecurityAPIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API security API params
func (o *PostAPISecurityAPIParams) WithContext(ctx context.Context) *PostAPISecurityAPIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API security API params
func (o *PostAPISecurityAPIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API security API params
func (o *PostAPISecurityAPIParams) WithHTTPClient(client *http.Client) *PostAPISecurityAPIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API security API params
func (o *PostAPISecurityAPIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API security API params
func (o *PostAPISecurityAPIParams) WithBody(body *models.APISecurityAPI) *PostAPISecurityAPIParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API security API params
func (o *PostAPISecurityAPIParams) SetBody(body *models.APISecurityAPI) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPISecurityAPIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
