// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPISecurityAPIReader is a Reader for the PostAPISecurityAPI structure.
type PostAPISecurityAPIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPISecurityAPIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPISecurityAPICreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostAPISecurityAPIUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPISecurityAPIForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPISecurityAPINotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPISecurityAPICreated creates a PostAPISecurityAPICreated with default headers values
func NewPostAPISecurityAPICreated() *PostAPISecurityAPICreated {
	return &PostAPISecurityAPICreated{}
}

/* PostAPISecurityAPICreated describes a response with status code 201, with default header values.

the new api id
*/
type PostAPISecurityAPICreated struct {
	Payload interface{}
}

func (o *PostAPISecurityAPICreated) Error() string {
	return fmt.Sprintf("[POST /apiSecurity/api][%d] postApiSecurityApiCreated  %+v", 201, o.Payload)
}
func (o *PostAPISecurityAPICreated) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAPISecurityAPICreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPISecurityAPIUnauthorized creates a PostAPISecurityAPIUnauthorized with default headers values
func NewPostAPISecurityAPIUnauthorized() *PostAPISecurityAPIUnauthorized {
	return &PostAPISecurityAPIUnauthorized{}
}

/* PostAPISecurityAPIUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type PostAPISecurityAPIUnauthorized struct {
}

func (o *PostAPISecurityAPIUnauthorized) Error() string {
	return fmt.Sprintf("[POST /apiSecurity/api][%d] postApiSecurityApiUnauthorized ", 401)
}

func (o *PostAPISecurityAPIUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPISecurityAPIForbidden creates a PostAPISecurityAPIForbidden with default headers values
func NewPostAPISecurityAPIForbidden() *PostAPISecurityAPIForbidden {
	return &PostAPISecurityAPIForbidden{}
}

/* PostAPISecurityAPIForbidden describes a response with status code 403, with default header values.

Forbidden. Api Security is disabled for user
*/
type PostAPISecurityAPIForbidden struct {
}

func (o *PostAPISecurityAPIForbidden) Error() string {
	return fmt.Sprintf("[POST /apiSecurity/api][%d] postApiSecurityApiForbidden ", 403)
}

func (o *PostAPISecurityAPIForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostAPISecurityAPINotFound creates a PostAPISecurityAPINotFound with default headers values
func NewPostAPISecurityAPINotFound() *PostAPISecurityAPINotFound {
	return &PostAPISecurityAPINotFound{}
}

/* PostAPISecurityAPINotFound describes a response with status code 404, with default header values.

Api with given catalogId does not exist
*/
type PostAPISecurityAPINotFound struct {
}

func (o *PostAPISecurityAPINotFound) Error() string {
	return fmt.Sprintf("[POST /apiSecurity/api][%d] postApiSecurityApiNotFound ", 404)
}

func (o *PostAPISecurityAPINotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
