// Code generated by go-swagger; DO NOT EDIT.

package api_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"io"
	"github.com/cisco-developer/api-insights/api/pkg/panoptica/models"
)

// PutAPISecurityOpenAPISpecsCatalogIDReader is a Reader for the PutAPISecurityOpenAPISpecsCatalogID structure.
type PutAPISecurityOpenAPISpecsCatalogIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPISecurityOpenAPISpecsCatalogIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutAPISecurityOpenAPISpecsCatalogIDCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPutAPISecurityOpenAPISpecsCatalogIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPISecurityOpenAPISpecsCatalogIDCreated creates a PutAPISecurityOpenAPISpecsCatalogIDCreated with default headers values
func NewPutAPISecurityOpenAPISpecsCatalogIDCreated() *PutAPISecurityOpenAPISpecsCatalogIDCreated {
	return &PutAPISecurityOpenAPISpecsCatalogIDCreated{}
}

/* PutAPISecurityOpenAPISpecsCatalogIDCreated describes a response with status code 201, with default header values.

Success
*/
type PutAPISecurityOpenAPISpecsCatalogIDCreated struct {
	Payload *models.OpenAPISpec
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDCreated) Error() string {
	return fmt.Sprintf("[PUT /apiSecurity/openApiSpecs/{catalogId}][%d] putApiSecurityOpenApiSpecsCatalogIdCreated  %+v", 201, o.Payload)
}
func (o *PutAPISecurityOpenAPISpecsCatalogIDCreated) GetPayload() *models.OpenAPISpec {
	return o.Payload
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenAPISpec)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAPISecurityOpenAPISpecsCatalogIDUnauthorized creates a PutAPISecurityOpenAPISpecsCatalogIDUnauthorized with default headers values
func NewPutAPISecurityOpenAPISpecsCatalogIDUnauthorized() *PutAPISecurityOpenAPISpecsCatalogIDUnauthorized {
	return &PutAPISecurityOpenAPISpecsCatalogIDUnauthorized{}
}

/* PutAPISecurityOpenAPISpecsCatalogIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type PutAPISecurityOpenAPISpecsCatalogIDUnauthorized struct {
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apiSecurity/openApiSpecs/{catalogId}][%d] putApiSecurityOpenApiSpecsCatalogIdUnauthorized ", 401)
}

func (o *PutAPISecurityOpenAPISpecsCatalogIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
