// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// APISecurityRiskSeverity RiskSeverity
//
// An `enum`eration.
//
// swagger:model ApiSecurityRiskSeverity
type APISecurityRiskSeverity string

func NewAPISecurityRiskSeverity(value APISecurityRiskSeverity) *APISecurityRiskSeverity {
	return &value
}

// Pointer returns a pointer to a freshly-allocated APISecurityRiskSeverity.
func (m APISecurityRiskSeverity) Pointer() *APISecurityRiskSeverity {
	return &m
}

const (

	// APISecurityRiskSeverityNORISK captures enum value "NO_RISK"
	APISecurityRiskSeverityNORISK APISecurityRiskSeverity = "NO_RISK"

	// APISecurityRiskSeverityUNKNOWN captures enum value "UNKNOWN"
	APISecurityRiskSeverityUNKNOWN APISecurityRiskSeverity = "UNKNOWN"

	// APISecurityRiskSeverityNEUTRAL captures enum value "NEUTRAL"
	APISecurityRiskSeverityNEUTRAL APISecurityRiskSeverity = "NEUTRAL"

	// APISecurityRiskSeverityLOW captures enum value "LOW"
	APISecurityRiskSeverityLOW APISecurityRiskSeverity = "LOW"

	// APISecurityRiskSeverityMEDIUM captures enum value "MEDIUM"
	APISecurityRiskSeverityMEDIUM APISecurityRiskSeverity = "MEDIUM"

	// APISecurityRiskSeverityHIGH captures enum value "HIGH"
	APISecurityRiskSeverityHIGH APISecurityRiskSeverity = "HIGH"

	// APISecurityRiskSeverityCRITICAL captures enum value "CRITICAL"
	APISecurityRiskSeverityCRITICAL APISecurityRiskSeverity = "CRITICAL"
)

// for schema
var apiSecurityRiskSeverityEnum []interface{}

func init() {
	var res []APISecurityRiskSeverity
	if err := json.Unmarshal([]byte(`["NO_RISK","UNKNOWN","NEUTRAL","LOW","MEDIUM","HIGH","CRITICAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiSecurityRiskSeverityEnum = append(apiSecurityRiskSeverityEnum, v)
	}
}

func (m APISecurityRiskSeverity) validateAPISecurityRiskSeverityEnum(path, location string, value APISecurityRiskSeverity) error {
	if err := validate.EnumCase(path, location, value, apiSecurityRiskSeverityEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this Api security risk severity
func (m APISecurityRiskSeverity) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPISecurityRiskSeverityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this Api security risk severity based on context it is used
func (m APISecurityRiskSeverity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
