// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIServiceDrillDownBase ApiService
//
// swagger:model ApiServiceDrillDownBase
type APIServiceDrillDownBase struct {

	// client workloads
	ClientWorkloads []*APIServiceClientWorkload `json:"clientWorkloads"`

	// compliance
	Compliance *APIServiceCompliance `json:"compliance,omitempty"`

	// Timestamp
	// Format: date-time
	CreationTimestamp strfmt.DateTime `json:"creation_timestamp,omitempty"`

	// Description
	//
	// Textual description of the Service
	Description string `json:"description,omitempty"`

	// Identifier
	//
	// Unique identifier of the subject API as assigned by Crankshaft
	// Required: true
	// Format: uuid
	Identifier *strfmt.UUID `json:"identifier"`

	// Link Doc
	//
	// Location of the documentation. This can be an URL for example
	LinkDoc string `json:"link_doc,omitempty"`

	// Name
	//
	// API name, usually an FQDN as determined by crankshaft, it can be logical or can correspond to one of the endpoints where the API is reachable, i.e. api.webex.com
	// Required: true
	Name *string `json:"name"`

	// risk
	Risk APISecurityRiskSeverity `json:"risk,omitempty"`

	// score
	Score *APIServiceScore `json:"score,omitempty"`

	// status
	Status APISecurityAPIStatus `json:"status,omitempty"`

	// status description
	StatusDescription string `json:"status_description,omitempty"`
}

// Validate validates this Api service drill down base
func (m *APIServiceDrillDownBase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientWorkloads(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompliance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreationTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRisk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceDrillDownBase) validateClientWorkloads(formats strfmt.Registry) error {
	if swag.IsZero(m.ClientWorkloads) { // not required
		return nil
	}

	for i := 0; i < len(m.ClientWorkloads); i++ {
		if swag.IsZero(m.ClientWorkloads[i]) { // not required
			continue
		}

		if m.ClientWorkloads[i] != nil {
			if err := m.ClientWorkloads[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clientWorkloads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("clientWorkloads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIServiceDrillDownBase) validateCompliance(formats strfmt.Registry) error {
	if swag.IsZero(m.Compliance) { // not required
		return nil
	}

	if m.Compliance != nil {
		if err := m.Compliance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("compliance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("compliance")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateCreationTimestamp(formats strfmt.Registry) error {
	if swag.IsZero(m.CreationTimestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_timestamp", "body", "date-time", m.CreationTimestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateIdentifier(formats strfmt.Registry) error {

	if err := validate.Required("identifier", "body", m.Identifier); err != nil {
		return err
	}

	if err := validate.FormatOf("identifier", "body", "uuid", m.Identifier.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateRisk(formats strfmt.Registry) error {
	if swag.IsZero(m.Risk) { // not required
		return nil
	}

	if err := m.Risk.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("risk")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("risk")
		}
		return err
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateScore(formats strfmt.Registry) error {
	if swag.IsZero(m.Score) { // not required
		return nil
	}

	if m.Score != nil {
		if err := m.Score.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("score")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("score")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceDrillDownBase) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("status")
		}
		return err
	}

	return nil
}

// ContextValidate validate this Api service drill down base based on the context it is used
func (m *APIServiceDrillDownBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateClientWorkloads(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCompliance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRisk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScore(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceDrillDownBase) contextValidateClientWorkloads(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ClientWorkloads); i++ {

		if m.ClientWorkloads[i] != nil {
			if err := m.ClientWorkloads[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clientWorkloads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("clientWorkloads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIServiceDrillDownBase) contextValidateCompliance(ctx context.Context, formats strfmt.Registry) error {

	if m.Compliance != nil {
		if err := m.Compliance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("compliance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("compliance")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceDrillDownBase) contextValidateRisk(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Risk.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("risk")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("risk")
		}
		return err
	}

	return nil
}

func (m *APIServiceDrillDownBase) contextValidateScore(ctx context.Context, formats strfmt.Registry) error {

	if m.Score != nil {
		if err := m.Score.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("score")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("score")
			}
			return err
		}
	}

	return nil
}

func (m *APIServiceDrillDownBase) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIServiceDrillDownBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIServiceDrillDownBase) UnmarshalBinary(b []byte) error {
	var res APIServiceDrillDownBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
