// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIServiceDrillDownExternal Api service drill down external
//
// swagger:model ApiServiceDrillDownExternal
type APIServiceDrillDownExternal struct {
	APIServiceDrillDownBase

	// Classification
	//
	// API classification label as determined by Crankshaft, e.g. ['meetings', 'messaging']
	Classification []string `json:"classification"`

	// provider
	Provider *APIProviderBase `json:"provider,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *APIServiceDrillDownExternal) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 APIServiceDrillDownBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.APIServiceDrillDownBase = aO0

	// AO1
	var dataAO1 struct {
		Classification []string `json:"classification"`

		Provider *APIProviderBase `json:"provider,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Classification = dataAO1.Classification

	m.Provider = dataAO1.Provider

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m APIServiceDrillDownExternal) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.APIServiceDrillDownBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Classification []string `json:"classification"`

		Provider *APIProviderBase `json:"provider,omitempty"`
	}

	dataAO1.Classification = m.Classification

	dataAO1.Provider = m.Provider

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this Api service drill down external
func (m *APIServiceDrillDownExternal) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIServiceDrillDownBase
	if err := m.APIServiceDrillDownBase.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceDrillDownExternal) validateProvider(formats strfmt.Registry) error {

	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	if m.Provider != nil {
		if err := m.Provider.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provider")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this Api service drill down external based on the context it is used
func (m *APIServiceDrillDownExternal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with APIServiceDrillDownBase
	if err := m.APIServiceDrillDownBase.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProvider(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceDrillDownExternal) contextValidateProvider(ctx context.Context, formats strfmt.Registry) error {

	if m.Provider != nil {
		if err := m.Provider.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provider")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIServiceDrillDownExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIServiceDrillDownExternal) UnmarshalBinary(b []byte) error {
	var res APIServiceDrillDownExternal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
