// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIProviderScoreGrade ApiProviderScoreGrade
//
// swagger:model ApiProviderScoreGrade
type APIProviderScoreGrade struct {

	// Additional Info
	AdditionalInfo []*AdditionalInfo `json:"additional_info"`

	// Avg Vulnerability Duration
	AvgVulnerabilityDuration int64 `json:"avg_vulnerability_duration,omitempty"`

	// Categories
	// Required: true
	Categories map[string]CategoryScoreGradeNoFindings `json:"categories"`

	// confidence
	Confidence RiskConfidenceEnum `json:"confidence,omitempty"`

	// Curated
	// Required: true
	Curated *bool `json:"curated"`

	// Last Finding Date
	// Format: date-time
	LastFindingDate strfmt.DateTime `json:"last_finding_date,omitempty"`

	// Last Vulnerability Date
	// Format: date-time
	LastVulnerabilityDate strfmt.DateTime `json:"last_vulnerability_date,omitempty"`

	// provider
	// Required: true
	Provider *APIProviderBase `json:"provider"`

	// provider id
	// Format: uuid
	ProviderID strfmt.UUID `json:"provider_id,omitempty"`

	// risk
	// Required: true
	Risk *APISecurityRiskSeverity `json:"risk"`

	// Scorer Version
	// Required: true
	ScorerVersion *int64 `json:"scorer_version"`

	// trend
	Trend RiskTrendEnum `json:"trend,omitempty"`
}

// Validate validates this Api provider score grade
func (m *APIProviderScoreGrade) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdditionalInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCategories(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfidence(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastFindingDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastVulnerabilityDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProviderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRisk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScorerVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrend(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIProviderScoreGrade) validateAdditionalInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.AdditionalInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.AdditionalInfo); i++ {
		if swag.IsZero(m.AdditionalInfo[i]) { // not required
			continue
		}

		if m.AdditionalInfo[i] != nil {
			if err := m.AdditionalInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additional_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additional_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIProviderScoreGrade) validateCategories(formats strfmt.Registry) error {

	if err := validate.Required("categories", "body", m.Categories); err != nil {
		return err
	}

	for k := range m.Categories {

		if err := validate.Required("categories"+"."+k, "body", m.Categories[k]); err != nil {
			return err
		}
		if val, ok := m.Categories[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("categories" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("categories" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIProviderScoreGrade) validateConfidence(formats strfmt.Registry) error {
	if swag.IsZero(m.Confidence) { // not required
		return nil
	}

	if err := m.Confidence.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidence")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("confidence")
		}
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateCurated(formats strfmt.Registry) error {

	if err := validate.Required("curated", "body", m.Curated); err != nil {
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateLastFindingDate(formats strfmt.Registry) error {
	if swag.IsZero(m.LastFindingDate) { // not required
		return nil
	}

	if err := validate.FormatOf("last_finding_date", "body", "date-time", m.LastFindingDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateLastVulnerabilityDate(formats strfmt.Registry) error {
	if swag.IsZero(m.LastVulnerabilityDate) { // not required
		return nil
	}

	if err := validate.FormatOf("last_vulnerability_date", "body", "date-time", m.LastVulnerabilityDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateProvider(formats strfmt.Registry) error {

	if err := validate.Required("provider", "body", m.Provider); err != nil {
		return err
	}

	if m.Provider != nil {
		if err := m.Provider.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provider")
			}
			return err
		}
	}

	return nil
}

func (m *APIProviderScoreGrade) validateProviderID(formats strfmt.Registry) error {
	if swag.IsZero(m.ProviderID) { // not required
		return nil
	}

	if err := validate.FormatOf("provider_id", "body", "uuid", m.ProviderID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateRisk(formats strfmt.Registry) error {

	if err := validate.Required("risk", "body", m.Risk); err != nil {
		return err
	}

	if err := validate.Required("risk", "body", m.Risk); err != nil {
		return err
	}

	if m.Risk != nil {
		if err := m.Risk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("risk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("risk")
			}
			return err
		}
	}

	return nil
}

func (m *APIProviderScoreGrade) validateScorerVersion(formats strfmt.Registry) error {

	if err := validate.Required("scorer_version", "body", m.ScorerVersion); err != nil {
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) validateTrend(formats strfmt.Registry) error {
	if swag.IsZero(m.Trend) { // not required
		return nil
	}

	if err := m.Trend.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("trend")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("trend")
		}
		return err
	}

	return nil
}

// ContextValidate validate this Api provider score grade based on the context it is used
func (m *APIProviderScoreGrade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdditionalInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCategories(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConfidence(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProvider(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRisk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTrend(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIProviderScoreGrade) contextValidateAdditionalInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdditionalInfo); i++ {

		if m.AdditionalInfo[i] != nil {
			if err := m.AdditionalInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additional_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additional_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIProviderScoreGrade) contextValidateCategories(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.Required("categories", "body", m.Categories); err != nil {
		return err
	}

	for k := range m.Categories {

		if val, ok := m.Categories[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *APIProviderScoreGrade) contextValidateConfidence(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Confidence.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidence")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("confidence")
		}
		return err
	}

	return nil
}

func (m *APIProviderScoreGrade) contextValidateProvider(ctx context.Context, formats strfmt.Registry) error {

	if m.Provider != nil {
		if err := m.Provider.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("provider")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("provider")
			}
			return err
		}
	}

	return nil
}

func (m *APIProviderScoreGrade) contextValidateRisk(ctx context.Context, formats strfmt.Registry) error {

	if m.Risk != nil {
		if err := m.Risk.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("risk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("risk")
			}
			return err
		}
	}

	return nil
}

func (m *APIProviderScoreGrade) contextValidateTrend(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Trend.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("trend")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("trend")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIProviderScoreGrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIProviderScoreGrade) UnmarshalBinary(b []byte) error {
	var res APIProviderScoreGrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
