// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// APIOrConditionsBase Api or conditions base
//
// swagger:discriminator ApiOrConditionsBase attribute
type APIOrConditionsBase interface {
	runtime.Validatable
	runtime.ContextValidatable

	// attribute
	// Required: true
	// Enum: [ApiRisk ApiRiskTrend ApiRiskTrendIsNone ApiRiskConfidence ApiRiskConfidenceIsNone ApiAvgVulnerabilityDuration ApiAvgVulnerabilityDurationIsNone ApiName ApiClassification ApiClassificationIsNone]
	Attribute() string
	SetAttribute(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type apiOrConditionsBase struct {
	attributeField string
}

// Attribute gets the attribute of this polymorphic type
func (m *apiOrConditionsBase) Attribute() string {
	return "ApiOrConditionsBase"
}

// SetAttribute sets the attribute of this polymorphic type
func (m *apiOrConditionsBase) SetAttribute(val string) {
}

// UnmarshalAPIOrConditionsBaseSlice unmarshals polymorphic slices of APIOrConditionsBase
func UnmarshalAPIOrConditionsBaseSlice(reader io.Reader, consumer runtime.Consumer) ([]APIOrConditionsBase, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []APIOrConditionsBase
	for _, element := range elements {
		obj, err := unmarshalAPIOrConditionsBase(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalAPIOrConditionsBase unmarshals polymorphic APIOrConditionsBase
func UnmarshalAPIOrConditionsBase(reader io.Reader, consumer runtime.Consumer) (APIOrConditionsBase, error) {
	// we need to read this twice, so first into a buffer
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalAPIOrConditionsBase(data, consumer)
}

func unmarshalAPIOrConditionsBase(data []byte, consumer runtime.Consumer) (APIOrConditionsBase, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the attribute property.
	var getType struct {
		Attribute string `json:"attribute"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("attribute", "body", getType.Attribute); err != nil {
		return nil, err
	}

	// The value of attribute is used to determine which type to create and unmarshal the data into
	switch getType.Attribute {
	case "ApiOrConditionsBase":
		var result apiOrConditionsBase
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid attribute value: %q", getType.Attribute)
}

// Validate validates this Api or conditions base
func (m *apiOrConditionsBase) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api or conditions base based on context it is used
func (m *apiOrConditionsBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
