// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIServiceProfileComplianceSimple ApiServiceProfileCompliance_Simple
//
// swagger:model ApiServiceProfileCompliance_Simple
type APIServiceProfileComplianceSimple struct {

	// Compliant
	// Required: true
	Compliant *bool `json:"compliant"`

	// Profile
	// Required: true
	Profile *string `json:"profile"`
}

// Validate validates this Api service profile compliance simple
func (m *APIServiceProfileComplianceSimple) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompliant(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIServiceProfileComplianceSimple) validateCompliant(formats strfmt.Registry) error {

	if err := validate.Required("compliant", "body", m.Compliant); err != nil {
		return err
	}

	return nil
}

func (m *APIServiceProfileComplianceSimple) validateProfile(formats strfmt.Registry) error {

	if err := validate.Required("profile", "body", m.Profile); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this Api service profile compliance simple based on context it is used
func (m *APIServiceProfileComplianceSimple) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIServiceProfileComplianceSimple) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIServiceProfileComplianceSimple) UnmarshalBinary(b []byte) error {
	var res APIServiceProfileComplianceSimple
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
