// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CategoryScoreGradeNoFindings CategoryScoreGradeNoFindings
//
// swagger:model CategoryScoreGradeNoFindings
type CategoryScoreGradeNoFindings struct {

	// Additional Info
	AdditionalInfo []*AdditionalInfo `json:"additional_info"`

	// confidence
	Confidence RiskConfidenceEnum `json:"confidence,omitempty"`

	// Critical
	// Required: true
	Critical *int64 `json:"critical"`

	// High
	// Required: true
	High *int64 `json:"high"`

	// Low
	// Required: true
	Low *int64 `json:"low"`

	// Medium
	// Required: true
	Medium *int64 `json:"medium"`

	// Name
	// Required: true
	Name *string `json:"name"`

	// risk
	// Required: true
	Risk *APISecurityRiskSeverity `json:"risk"`

	// Scorer Version
	// Required: true
	ScorerVersion *int64 `json:"scorer_version"`

	// trend
	Trend RiskTrendEnum `json:"trend,omitempty"`

	// Unclassified
	// Required: true
	Unclassified *int64 `json:"unclassified"`
}

// Validate validates this category score grade no findings
func (m *CategoryScoreGradeNoFindings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdditionalInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfidence(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCritical(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHigh(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLow(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedium(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRisk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScorerVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrend(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnclassified(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryScoreGradeNoFindings) validateAdditionalInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.AdditionalInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.AdditionalInfo); i++ {
		if swag.IsZero(m.AdditionalInfo[i]) { // not required
			continue
		}

		if m.AdditionalInfo[i] != nil {
			if err := m.AdditionalInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additional_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additional_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateConfidence(formats strfmt.Registry) error {
	if swag.IsZero(m.Confidence) { // not required
		return nil
	}

	if err := m.Confidence.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidence")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("confidence")
		}
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateCritical(formats strfmt.Registry) error {

	if err := validate.Required("critical", "body", m.Critical); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateHigh(formats strfmt.Registry) error {

	if err := validate.Required("high", "body", m.High); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateLow(formats strfmt.Registry) error {

	if err := validate.Required("low", "body", m.Low); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateMedium(formats strfmt.Registry) error {

	if err := validate.Required("medium", "body", m.Medium); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateRisk(formats strfmt.Registry) error {

	if err := validate.Required("risk", "body", m.Risk); err != nil {
		return err
	}

	if err := validate.Required("risk", "body", m.Risk); err != nil {
		return err
	}

	if m.Risk != nil {
		if err := m.Risk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("risk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("risk")
			}
			return err
		}
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateScorerVersion(formats strfmt.Registry) error {

	if err := validate.Required("scorer_version", "body", m.ScorerVersion); err != nil {
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateTrend(formats strfmt.Registry) error {
	if swag.IsZero(m.Trend) { // not required
		return nil
	}

	if err := m.Trend.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("trend")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("trend")
		}
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) validateUnclassified(formats strfmt.Registry) error {

	if err := validate.Required("unclassified", "body", m.Unclassified); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this category score grade no findings based on the context it is used
func (m *CategoryScoreGradeNoFindings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdditionalInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConfidence(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRisk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTrend(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryScoreGradeNoFindings) contextValidateAdditionalInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdditionalInfo); i++ {

		if m.AdditionalInfo[i] != nil {
			if err := m.AdditionalInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("additional_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("additional_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) contextValidateConfidence(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Confidence.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidence")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("confidence")
		}
		return err
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) contextValidateRisk(ctx context.Context, formats strfmt.Registry) error {

	if m.Risk != nil {
		if err := m.Risk.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("risk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("risk")
			}
			return err
		}
	}

	return nil
}

func (m *CategoryScoreGradeNoFindings) contextValidateTrend(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Trend.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("trend")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("trend")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CategoryScoreGradeNoFindings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryScoreGradeNoFindings) UnmarshalBinary(b []byte) error {
	var res CategoryScoreGradeNoFindings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
