// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// EndpointOrConditionsBase endpoint or conditions base
//
// swagger:discriminator EndpointOrConditionsBase attribute
type EndpointOrConditionsBase interface {
	runtime.Validatable
	runtime.ContextValidatable

	// attribute
	// Required: true
	// Enum: [EndpointRisk EndpointRiskTrend EndpointRiskTrendIsNone EndpointRiskConfidence EndpointRiskConfidenceIsNone EndpointLocation EndpointLocationIsNone EndpointHostV4 EndpointHostV6 EndpointHostname EndpointHostnameIsNone EndpointScheme EndpointSchemeIsNone EndpointProtocol EndpointPort]
	Attribute() string
	SetAttribute(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type endpointOrConditionsBase struct {
	attributeField string
}

// Attribute gets the attribute of this polymorphic type
func (m *endpointOrConditionsBase) Attribute() string {
	return "EndpointOrConditionsBase"
}

// SetAttribute sets the attribute of this polymorphic type
func (m *endpointOrConditionsBase) SetAttribute(val string) {
}

// UnmarshalEndpointOrConditionsBaseSlice unmarshals polymorphic slices of EndpointOrConditionsBase
func UnmarshalEndpointOrConditionsBaseSlice(reader io.Reader, consumer runtime.Consumer) ([]EndpointOrConditionsBase, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []EndpointOrConditionsBase
	for _, element := range elements {
		obj, err := unmarshalEndpointOrConditionsBase(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalEndpointOrConditionsBase unmarshals polymorphic EndpointOrConditionsBase
func UnmarshalEndpointOrConditionsBase(reader io.Reader, consumer runtime.Consumer) (EndpointOrConditionsBase, error) {
	// we need to read this twice, so first into a buffer
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalEndpointOrConditionsBase(data, consumer)
}

func unmarshalEndpointOrConditionsBase(data []byte, consumer runtime.Consumer) (EndpointOrConditionsBase, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the attribute property.
	var getType struct {
		Attribute string `json:"attribute"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("attribute", "body", getType.Attribute); err != nil {
		return nil, err
	}

	// The value of attribute is used to determine which type to create and unmarshal the data into
	switch getType.Attribute {
	case "EndpointOrConditionsBase":
		var result endpointOrConditionsBase
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid attribute value: %q", getType.Attribute)
}

// Validate validates this endpoint or conditions base
func (m *endpointOrConditionsBase) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this endpoint or conditions base based on context it is used
func (m *endpointOrConditionsBase) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
