// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OpenAPISpecPreview open Api spec preview
//
// swagger:model OpenApiSpecPreview
type OpenAPISpecPreview struct {

	// base path
	BasePath string `json:"basePath,omitempty"`

	// contact mail
	ContactMail string `json:"contactMail,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// license name
	LicenseName string `json:"licenseName,omitempty"`

	// license Url
	LicenseURL string `json:"licenseUrl,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// terms of service
	TermsOfService string `json:"termsOfService,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this open Api spec preview
func (m *OpenAPISpecPreview) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this open Api spec preview based on context it is used
func (m *OpenAPISpecPreview) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenAPISpecPreview) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenAPISpecPreview) UnmarshalBinary(b []byte) error {
	var res OpenAPISpecPreview
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
