// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OpenAPISpecScoreComponentsV3ElementsList open Api spec score components v3 elements list
//
// swagger:model OpenApiSpecScoreComponentsV3ElementsList
type OpenAPISpecScoreComponentsV3ElementsList struct {
	OpenAPISpecScoreElementsList

	// Name
	Name string `json:"name,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *OpenAPISpecScoreComponentsV3ElementsList) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 OpenAPISpecScoreElementsList
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.OpenAPISpecScoreElementsList = aO0

	// AO1
	var dataAO1 struct {
		Name string `json:"name,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Name = dataAO1.Name

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m OpenAPISpecScoreComponentsV3ElementsList) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.OpenAPISpecScoreElementsList)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Name string `json:"name,omitempty"`
	}

	dataAO1.Name = m.Name

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this open Api spec score components v3 elements list
func (m *OpenAPISpecScoreComponentsV3ElementsList) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OpenAPISpecScoreElementsList
	if err := m.OpenAPISpecScoreElementsList.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this open Api spec score components v3 elements list based on the context it is used
func (m *OpenAPISpecScoreComponentsV3ElementsList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with OpenAPISpecScoreElementsList
	if err := m.OpenAPISpecScoreElementsList.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenAPISpecScoreComponentsV3ElementsList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenAPISpecScoreComponentsV3ElementsList) UnmarshalBinary(b []byte) error {
	var res OpenAPISpecScoreComponentsV3ElementsList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
