// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SpecMethod spec method
//
// swagger:model SpecMethod
type SpecMethod struct {

	// description
	Description string `json:"description,omitempty"`

	// findings
	Findings *SpecScoreFindings `json:"findings,omitempty"`

	// method
	Method HTTPMethod `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// severity
	Severity APISecurityRiskSeverity `json:"severity,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`
}

// Validate validates this spec method
func (m *SpecMethod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFindings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SpecMethod) validateFindings(formats strfmt.Registry) error {
	if swag.IsZero(m.Findings) { // not required
		return nil
	}

	if m.Findings != nil {
		if err := m.Findings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("findings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("findings")
			}
			return err
		}
	}

	return nil
}

func (m *SpecMethod) validateMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.Method) { // not required
		return nil
	}

	if err := m.Method.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("method")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("method")
		}
		return err
	}

	return nil
}

func (m *SpecMethod) validateSeverity(formats strfmt.Registry) error {
	if swag.IsZero(m.Severity) { // not required
		return nil
	}

	if err := m.Severity.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("severity")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("severity")
		}
		return err
	}

	return nil
}

// ContextValidate validate this spec method based on the context it is used
func (m *SpecMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFindings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMethod(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSeverity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SpecMethod) contextValidateFindings(ctx context.Context, formats strfmt.Registry) error {

	if m.Findings != nil {
		if err := m.Findings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("findings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("findings")
			}
			return err
		}
	}

	return nil
}

func (m *SpecMethod) contextValidateMethod(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Method.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("method")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("method")
		}
		return err
	}

	return nil
}

func (m *SpecMethod) contextValidateSeverity(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Severity.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("severity")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("severity")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SpecMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SpecMethod) UnmarshalBinary(b []byte) error {
	var res SpecMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
